repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.5.0"
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
      exclude: \.vscode/launch\.json
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix]
      exclude: \.vscode/launch\.json
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/pycqa/isort
  rev: "5.13.2"
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/psf/black
  rev: "24.3.0"
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: "7.0.0"
  hooks:
    - id: flake8
#- repo: https://github.com/koalaman/shellcheck-precommit
#  rev: "v0.10.0"
#  hooks:
#    - id: shellcheck
#      args: ["--exclude=SC2148"]
