# Generated by Django 5.0 on 2024-12-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
